export const ModelProvider = {
  BaiZhiCloud: {
    label: 'BaiZhiCloud',
    cn: '百智云',
    icon: 'icon-baizhiyunlogo',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://model-square.app.baizhi.cloud/token',
    defaultBaseUrl: 'https://model-square.app.baizhi.cloud/v1',
  },
  DeepSeek: {
    label: 'DeepSeek',
    cn: '',
    icon: 'icon-deepseek',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.deepseek.com/api_keys',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
  },
  Hunyuan: {
    label: 'Hunyuan',
    cn: '腾讯混元',
    icon: 'icon-tengxunhunyuan',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://console.cloud.tencent.com/hunyuan/start',
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
  },
  BaiLian: {
    label: 'BaiLian',
    cn: '阿里云百炼',
    icon: 'icon-aliyunbailian',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://bailian.console.aliyun.com/?tab=model#/api-key',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
  Volcengine: {
    label: 'Volcengine',
    cn: '火山引擎',
    icon: 'icon-huoshanyinqing',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl:
      'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
  },
  OpenAI: {
    label: 'OpenAI',
    cn: '',
    icon: 'icon-chatgpt',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.openai.com/api-keys',
    defaultBaseUrl: 'https://api.openai.com/v1',
  },
  Ollama: {
    label: 'Ollama',
    cn: '',
    icon: 'icon-ollama',
    urlWrite: true,
    secretRequired: false,
    customHeader: true,
    modelDocumentUrl: '',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
  },
  SiliconFlow: {
    label: 'SiliconFlow',
    cn: '硅基流动',
    icon: 'icon-a-ziyuan2',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://cloud.siliconflow.cn/account/ak',
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
  },
  Moonshot: {
    label: 'Moonshot',
    cn: '月之暗面',
    icon: 'icon-Kim',
    urlWrite: false,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: 'https://platform.moonshot.cn/console/api-keys',
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
  },
  AzureOpenAI: {
    label: 'AzureOpenAI',
    cn: 'Azure OpenAI',
    icon: 'icon-azure',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl:
      'https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI',
    defaultBaseUrl: 'https://<resource_name>.openai.azure.com',
  },
  Other: {
    label: 'Other',
    cn: '其他',
    icon: 'icon-a-AIshezhi',
    urlWrite: true,
    secretRequired: true,
    customHeader: false,
    modelDocumentUrl: '',
    defaultBaseUrl: '',
  },
};
