ALTER TABLE models ADD COLUMN IF NOT EXISTS show_name VARCHAR(255);
ALTER TABLE models ADD COLUMN IF NOT EXISTS api_version VARCHAR(255);
ALTER TABLE models ADD COLUMN IF NOT EXISTS api_header TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS is_internal BOOLEAN DEFAULT false;