// Code generated by ent, DO NOT EDIT.

package billingquota

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/chaitin/MonkeyCode/backend/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldContainsFold(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldUserID, v))
}

// Total applies equality check predicate on the "total" field. It's identical to TotalEQ.
func Total(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldTotal, v))
}

// Used applies equality check predicate on the "used" field. It's identical to UsedEQ.
func Used(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldUsed, v))
}

// Remain applies equality check predicate on the "remain" field. It's identical to RemainEQ.
func Remain(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldRemain, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldContainsFold(FieldUserID, v))
}

// TotalEQ applies the EQ predicate on the "total" field.
func TotalEQ(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldTotal, v))
}

// TotalNEQ applies the NEQ predicate on the "total" field.
func TotalNEQ(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldTotal, v))
}

// TotalIn applies the In predicate on the "total" field.
func TotalIn(vs ...int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldTotal, vs...))
}

// TotalNotIn applies the NotIn predicate on the "total" field.
func TotalNotIn(vs ...int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldTotal, vs...))
}

// TotalGT applies the GT predicate on the "total" field.
func TotalGT(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldTotal, v))
}

// TotalGTE applies the GTE predicate on the "total" field.
func TotalGTE(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldTotal, v))
}

// TotalLT applies the LT predicate on the "total" field.
func TotalLT(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldTotal, v))
}

// TotalLTE applies the LTE predicate on the "total" field.
func TotalLTE(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldTotal, v))
}

// UsedEQ applies the EQ predicate on the "used" field.
func UsedEQ(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldUsed, v))
}

// UsedNEQ applies the NEQ predicate on the "used" field.
func UsedNEQ(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldUsed, v))
}

// UsedIn applies the In predicate on the "used" field.
func UsedIn(vs ...int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldUsed, vs...))
}

// UsedNotIn applies the NotIn predicate on the "used" field.
func UsedNotIn(vs ...int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldUsed, vs...))
}

// UsedGT applies the GT predicate on the "used" field.
func UsedGT(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldUsed, v))
}

// UsedGTE applies the GTE predicate on the "used" field.
func UsedGTE(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldUsed, v))
}

// UsedLT applies the LT predicate on the "used" field.
func UsedLT(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldUsed, v))
}

// UsedLTE applies the LTE predicate on the "used" field.
func UsedLTE(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldUsed, v))
}

// RemainEQ applies the EQ predicate on the "remain" field.
func RemainEQ(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldRemain, v))
}

// RemainNEQ applies the NEQ predicate on the "remain" field.
func RemainNEQ(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldRemain, v))
}

// RemainIn applies the In predicate on the "remain" field.
func RemainIn(vs ...int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldRemain, vs...))
}

// RemainNotIn applies the NotIn predicate on the "remain" field.
func RemainNotIn(vs ...int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldRemain, vs...))
}

// RemainGT applies the GT predicate on the "remain" field.
func RemainGT(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldRemain, v))
}

// RemainGTE applies the GTE predicate on the "remain" field.
func RemainGTE(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldRemain, v))
}

// RemainLT applies the LT predicate on the "remain" field.
func RemainLT(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldRemain, v))
}

// RemainLTE applies the LTE predicate on the "remain" field.
func RemainLTE(v int64) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldRemain, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingQuota {
	return predicate.BillingQuota(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingQuota) predicate.BillingQuota {
	return predicate.BillingQuota(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingQuota) predicate.BillingQuota {
	return predicate.BillingQuota(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingQuota) predicate.BillingQuota {
	return predicate.BillingQuota(sql.NotPredicates(p))
}
